services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: am/bpoe-api-ocr:latest
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/
    env_file:
      - .env
    networks:
      - minionetwork
    depends_on:
      minio:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ../log:/log

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z-cpuv1
    env_file:
      - .env
    restart: unless-stopped
    ports:
#      - '9000:9000'
      - '127.0.0.1:9001:9001'  # WebUI MinIO
    networks:
      - minionetwork
    volumes:
      - '../temp/minio_data:/data'
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ] # Użyj Minio Client (mc) do sprawdzenia gotowości
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  minionetwork:
    driver: bridge
